# app_handler API接口测试
@id = d7664ea4-4b0b-408d-b667-0504c11448eb
@moudle = apps
@app_id = d7664ea4-4b0b-408d-b667-0504c11448eb

### 删除 App 记录
POST {{host}}/{{moudle}}/{{id}}/delete
Content-Type: application/json

### 修改 App 记录
POST {{host}}/{{moudle}}/{{id}}
Content-Type: application/json

### 获取 App 记录
GET {{host}}/{{moudle}}/{{id}}
Accept: application/json

### 创建 App 记录
POST {{host}}/{{moudle}}/create
Content-Type: application/json

### AI应用接口调试
POST {{host}}/{{moudle}}/{{app_id}}/debug
Content-Type: application/json

{
    "query": "你好，你是谁？"
}

###
