# app_handler API接口测试
@id = 8e86af99-8f97-44e4-8253-b14e753d84e9

### 删除 App 记录
POST {{host}}/app/{{id}}/delete
Content-Type: application/json

### 修改 App 记录
POST {{host}}/app/{{id}}
Content-Type: application/json

### 获取 App 记录
GET {{host}}/app/{{id}}
Accept: application/json

### 创建 App 记录
POST {{host}}/app/create
Content-Type: application/json

### 机器人聊天接口
POST {{host}}/app/completion
Content-Type: application/json

{
    "query": "你好，你是谁？"
}

###
