# app_handler API接口测试
@hostname = http://127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
@module = apps
@app_id = 9495d2e2-2e7a-4484-8447-03f6b24627f7

### 删除 App 记录
POST {{host}}/{{module}}/{{app_id}}/delete
Content-Type: application/json

### 修改 App 记录
POST {{host}}/{{module}}/{{app_id}}
Content-Type: application/json

### 获取 App 记录
GET {{host}}/{{module}}/{{app_id}}
Accept: application/json

### 创建 App 记录
POST {{host}}/{{module}}/create
Content-Type: application/json

### AI应用接口调试
POST {{host}}/{{module}}/{{app_id}}/debug
Content-Type: application/json

{
    "query": "你好，你是谁？"
}

###
