"""empty message

Revision ID: 101ce91b2620
Revises: d5fd01c86667
Create Date: 2026-03-08 17:32:00.598135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101ce91b2620'
down_revision = 'd5fd01c86667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduct_from', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.drop_column('deduct_from')

    # ### end Alembic commands ###
