"""empty message

Revision ID: 1fd4978744ae
Revises: 5a59802a930f
Create Date: 2026-01-12 04:30:41.915290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd4978744ae'
down_revision = '5a59802a930f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
