"""empty message

Revision ID: 4fd9c10ed9eb
Revises: e1b7f90fa81e
Create Date: 2026-03-07 01:17:56.310936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd9c10ed9eb'
down_revision = 'e1b7f90fa81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###
