"""empty message

Revision ID: 5c780a13dcee
Revises: fe84206900bf
Create Date: 2026-02-22 02:22:32.306884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c780a13dcee'
down_revision = 'fe84206900bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('account')

    # ### end Alembic commands ###
