"""empty message

Revision ID: 7063fb9b0750
Revises: 20fb83cde96a
Create Date: 2025-12-01 23:36:11.500027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7063fb9b0750'
down_revision = '20fb83cde96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_id')
    )
    op.create_table('account_oauth',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('openid', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('encrypted_token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_oauth_id'),
    sa.UniqueConstraint('account_id', 'provider', name='uk_account_oauth_account_id_provider'),
    sa.UniqueConstraint('provider', 'openid', name='uk_account_oauth_provider_openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_oauth')
    op.drop_table('account')
    # ### end Alembic commands ###
