"""empty message

Revision ID: 715760a6854c
Revises: cd0c6659909c
Create Date: 2025-11-12 22:21:48.988332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '715760a6854c'
down_revision = 'cd0c6659909c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('stopped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stopped', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('stopped_at')

    # ### end Alembic commands ###
