"""empty message

Revision ID: 8ead8a3f1632
Revises: e3d3550f088e
Create Date: 2026-03-04 20:10:07.482105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ead8a3f1632'
down_revision = 'e3d3550f088e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unionid', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('wechat_nickname', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('wechat_avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('wechat_gender', sa.SMALLINT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('wechat_country', sa.String(length=50), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('wechat_province', sa.String(length=50), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('wechat_city', sa.String(length=50), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=True))
        batch_op.create_index('idx_account_oauth_unionid_provider', ['unionid', 'provider'], unique=False)
        batch_op.create_unique_constraint('uk_account_oauth_provider_unionid', ['provider', 'unionid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_constraint('uk_account_oauth_provider_unionid', type_='unique')
        batch_op.drop_index('idx_account_oauth_unionid_provider')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('wechat_city')
        batch_op.drop_column('wechat_province')
        batch_op.drop_column('wechat_country')
        batch_op.drop_column('wechat_gender')
        batch_op.drop_column('wechat_avatar')
        batch_op.drop_column('wechat_nickname')
        batch_op.drop_column('unionid')

    # ### end Alembic commands ###
