"""empty message

Revision ID: 99f4ebf5df88
Revises: 1a481bba6cf4
Create Date: 2026-02-06 17:00:05.536050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f4ebf5df88'
down_revision = '1a481bba6cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('idx_account_email', ['email'], unique=False)

    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.create_index('idx_account_oauth_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_account_oauth_openid_provider', ['openid', 'provider'], unique=False)

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('idx_api_key_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_api_key_api_key', ['api_key'], unique=False)

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('idx_app_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_app_token', ['token'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('conversation_app_created_by_idx'))
        batch_op.drop_index(batch_op.f('conversation_app_id_idx'))
        batch_op.create_index('idx_conversation_app_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_conversation_app_id', ['app_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('message_conversation_id_idx'))
        batch_op.drop_index(batch_op.f('message_created_by_idx'))
        batch_op.create_index('idx_message_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_message_created_by', ['created_by'], unique=False)

    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('message_agent_thought_app_id_idx'))
        batch_op.drop_index(batch_op.f('message_agent_thought_conversation_id_idx'))
        batch_op.drop_index(batch_op.f('message_agent_thought_message_id_idx'))
        batch_op.create_index('idx_message_agent_thought_app_id', ['app_id'], unique=False)
        batch_op.create_index('idx_message_agent_thought_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_message_agent_thought_message_id', ['message_id'], unique=False)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_workflow_tool_call_name', ['tool_call_name'], unique=False)

    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_result_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_workflow_result_app_id', ['app_id'], unique=False)
        batch_op.create_index('idx_workflow_result_workflow_id', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_result_workflow_id')
        batch_op.drop_index('idx_workflow_result_app_id')
        batch_op.drop_index('idx_workflow_result_account_id')

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_tool_call_name')
        batch_op.drop_index('idx_workflow_account_id')

    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_index('idx_message_agent_thought_message_id')
        batch_op.drop_index('idx_message_agent_thought_conversation_id')
        batch_op.drop_index('idx_message_agent_thought_app_id')
        batch_op.create_index(batch_op.f('message_agent_thought_message_id_idx'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('message_agent_thought_conversation_id_idx'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('message_agent_thought_app_id_idx'), ['app_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_created_by')
        batch_op.drop_index('idx_message_conversation_id')
        batch_op.create_index(batch_op.f('message_created_by_idx'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('message_conversation_id_idx'), ['conversation_id'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('idx_conversation_app_id')
        batch_op.drop_index('idx_conversation_app_created_by')
        batch_op.create_index(batch_op.f('conversation_app_id_idx'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('conversation_app_created_by_idx'), ['created_by'], unique=False)

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('idx_app_token')
        batch_op.drop_index('idx_app_account_id')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index('idx_api_key_api_key')
        batch_op.drop_index('idx_api_key_account_id')

    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_index('idx_account_oauth_openid_provider')
        batch_op.drop_index('idx_account_oauth_account_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('idx_account_email')

    # ### end Alembic commands ###
