"""empty message

Revision ID: b1814abe3761
Revises: 14c52d515544
Create Date: 2025-12-22 04:41:09.392505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1814abe3761'
down_revision = '14c52d515544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('remark', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_api_key_id'),
    sa.UniqueConstraint('account_id', 'api_key', name='uk_api_key_account_id_api_key'),
    sa.UniqueConstraint('api_key', name='uk_api_key_api_key')
    )
    op.create_table('end_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_end_user_id'),
    sa.UniqueConstraint('tenant_id', 'app_id', 'id', name='uk_end_user_tenant_app_id')
    )
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index('idx_end_user_app_id', ['app_id'], unique=False)
        batch_op.create_index('idx_end_user_tenant_app', ['tenant_id', 'app_id'], unique=False)
        batch_op.create_index('idx_end_user_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index('idx_end_user_tenant_id')
        batch_op.drop_index('idx_end_user_tenant_app')
        batch_op.drop_index('idx_end_user_app_id')

    op.drop_table('end_user')
    op.drop_table('api_key')
    # ### end Alembic commands ###
