"""empty message

Revision ID: c03f607acdb7
Revises: 715760a6854c
Create Date: 2025-11-12 22:39:25.117904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c03f607acdb7'
down_revision = '715760a6854c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('stopped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stopped', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('stopped_at')

    # ### end Alembic commands ###
