"""empty message

Revision ID: d5fd01c86667
Revises: 4fd9c10ed9eb
Create Date: 2026-03-07 02:07:13.512839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fd01c86667'
down_revision = '4fd9c10ed9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_points', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('available_points',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('frozen_points',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.alter_column('points_amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('recharge_order', schema=None) as batch_op:
        batch_op.alter_column('points_amount',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recharge_order', schema=None) as batch_op:
        batch_op.alter_column('points_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.alter_column('points_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('account_points', schema=None) as batch_op:
        batch_op.alter_column('frozen_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('available_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_points',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
