"""empty message

Revision ID: e1b7f90fa81e
Revises: 8ead8a3f1632
Create Date: 2026-03-05 18:33:12.738789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1b7f90fa81e'
down_revision = '8ead8a3f1632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_account_oauth_unionid_provider'))
        batch_op.drop_constraint(batch_op.f('uk_account_oauth_provider_unionid'), type_='unique')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('wechat_city')
        batch_op.drop_column('wechat_gender')
        batch_op.drop_column('wechat_avatar')
        batch_op.drop_column('wechat_province')
        batch_op.drop_column('wechat_country')
        batch_op.drop_column('wechat_nickname')
        batch_op.drop_column('unionid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unionid', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_nickname', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_country', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_province', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_avatar', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_gender', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wechat_city', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uk_account_oauth_provider_unionid'), ['provider', 'unionid'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_account_oauth_unionid_provider'), ['unionid', 'provider'], unique=False)

    # ### end Alembic commands ###
