"""empty message

Revision ID: e3d3550f088e
Revises: 5c780a13dcee
Create Date: 2026-03-04 12:09:44.515168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3d3550f088e'
down_revision = '5c780a13dcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_points',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('total_points', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_points', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('frozen_points', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_points_id')
    )
    with op.batch_alter_table('account_points', schema=None) as batch_op:
        batch_op.create_index('idx_account_points_account_id', ['account_id'], unique=False)

    op.create_table('points_transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points_amount', sa.BigInteger(), nullable=False),
    sa.Column('token_amount', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('transaction_desc', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('transaction_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_points_transaction_id')
    )
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.create_index('idx_points_transaction_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_points_transaction_message_id', ['message_id'], unique=False)
        batch_op.create_index('idx_points_transaction_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_points_transaction_transaction_type', ['transaction_type'], unique=False)

    op.create_table('recharge_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('points_amount', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_status', sa.String(length=20), server_default=sa.text("'UNPAID'"), nullable=False),
    sa.Column('pay_channel', sa.String(length=50), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('refund_time', sa.DateTime(), nullable=True),
    sa.Column('order_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_recharge_order_id'),
    sa.UniqueConstraint('order_no')
    )
    with op.batch_alter_table('recharge_order', schema=None) as batch_op:
        batch_op.create_index('idx_recharge_order_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_recharge_order_order_no', ['order_no'], unique=False)
        batch_op.create_index('idx_recharge_order_pay_status', ['pay_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recharge_order', schema=None) as batch_op:
        batch_op.drop_index('idx_recharge_order_pay_status')
        batch_op.drop_index('idx_recharge_order_order_no')
        batch_op.drop_index('idx_recharge_order_account_id')

    op.drop_table('recharge_order')
    with op.batch_alter_table('points_transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_points_transaction_transaction_type')
        batch_op.drop_index('idx_points_transaction_order_id')
        batch_op.drop_index('idx_points_transaction_message_id')
        batch_op.drop_index('idx_points_transaction_account_id')

    op.drop_table('points_transaction')
    with op.batch_alter_table('account_points', schema=None) as batch_op:
        batch_op.drop_index('idx_account_points_account_id')

    op.drop_table('account_points')
    # ### end Alembic commands ###
