DEFAULT_CONFIG = {
    # CSRF（跨站请求伪造）保护
    "WTF_CSRF_ENABLED": "False",
    # 数据库配置
    "SQLALCHEMY_DATABASE_URI": "",
    "SQLALCHEMY_POOL_SIZE": 30,
    "SQLALCHEMY_POOL_RECYCLE": 3600,
    "SQLALCHEMY_ECHO": "True",
}
